# ai_legal_analyzer.py
# Core script for Perjury and Contradiction Analysis using Gemini API

import os
import glob
import pandas as pd
from google import genai
from google.genai.errors import APIError
import json

# --- Configuration ---
# Secure API key management
from config.api_keys import get_api_keys

try:
    # Get API keys securely
    keys = get_api_keys()
    # Configure Gemini
    genai.configure(api_key=keys['gemini'])
    client = genai.Client()
except Exception as e:
    print(f"Error initializing Gemini client: {e}")
    print("Please ensure GEMINI_API_KEY is properly configured in .env file")
    exit()

# File paths
OUTPUT_DIR = 'output'
MASTER_CSV = None # Will be determined dynamically
ANALYSIS_OUTPUT_CSV = os.path.join(OUTPUT_DIR, 'AI_CONTRADICTION_REPORT.csv')

# Key documents for analysis (Harper's case specific)
APPLICANT_FILINGS = {
    'Initial_Affidavit_FDSJ739': "The Applicant claims they are financially stable and can provide adequate care for Harper.",
    'Substance_Use_Claims': "The Applicant stated under oath that they have never consumed substances around the child.",
    'Parenting_Capability_Claims': "The Applicant stated they are capable of providing consistent, safe care and following court orders.",
    'Criminal_Assault_Incident_Dec9': "The incident on December 9, 2024, which led to criminal charges for assault.",
    'Communication_Pattern_Claims': "The Applicant claims they communicate respectfully and cooperatively regarding custody matters."
}

def find_latest_evidence_file():
    """Finds the most recent 'enhanced_ocr_results' CSV file in the output directory."""
    search_pattern = os.path.join(OUTPUT_DIR, 'enhanced_ocr_results_*.csv')
    files = glob.glob(search_pattern)
    if not files:
        # Fallback to older file patterns if new one isn't found
        search_pattern = os.path.join(OUTPUT_DIR, 'ocr_results_*.csv')
        files = glob.glob(search_pattern)
    
    if not files:
        return None
        
    latest_file = max(files, key=os.path.getmtime)
    return latest_file

def load_evidence(file_path):
    """Loads the master evidence CSV generated by the OCR processor."""
    if not os.path.exists(file_path):
        print(f"Error: Master evidence file not found at {file_path}")
        return None
    return pd.read_csv(file_path)

def analyze_for_contradiction(df, filing_name, filing_statement):
    """
    Uses Gemini to analyze evidence log entries against a specific sworn statement.
    """
    print(f"\n--- Analyzing against: {filing_name} ---")
    
    contradictions = []

    # Get the key factual statements from the OCR log
    # Use both raw_text and formatted_text columns if available
    if 'raw_text' in df.columns:
        evidence_text = "\n".join(df['raw_text'].astype(str).tolist())
    elif 'Key_Factual_Statement' in df.columns:
        evidence_text = "\n".join(df['Key_Factual_Statement'].astype(str).tolist())
    elif 'formatted_text' in df.columns:
        evidence_text = "\n".join(df['formatted_text'].astype(str).tolist())
    else:
        print(f"Error: No text content column found in CSV")
        return pd.DataFrame()
    
    # Limit to first 4000 chars for efficiency
    evidence_text = evidence_text[:4000]
    
    # Construct the highly specific, legally-focused prompt
    prompt = f"""
    You are a legal evidence analyst specializing in family law and custody cases. Your task is to compare a collection of evidence against a specific sworn statement to detect contradictions, contempt, or falsehoods (perjury).

    **Context**: This is evidence from Harper's custody case (FDSJ739). The evidence consists of text messages, communications, and documents extracted via OCR.

    **Sworn Statement to Analyze**: "{filing_statement}"

    **Collected Evidence (OCR Text):**
    ---
    {evidence_text}
    ---

    Carefully review the evidence text. Identify any statements or recorded facts that directly contradict the sworn statement, or that demonstrate a pattern of conduct inconsistent with the statement. Focus on:
    - Financial instability contradicting financial stability claims
    - Substance use evidence contradicting sobriety claims  
    - Hostile/threatening communication contradicting cooperation claims
    - Inability to follow orders contradicting parenting capability claims
    - Evidence of the December 9, 2024 assault incident

    Output ONLY a JSON array of objects. Each object must contain:
    1. 'Filing_ID': The unique ID '{filing_name}'.
    2. 'Contradicted_Statement': A concise summary of the contradicted claim.
    3. 'Evidence_Snippet': The most relevant, direct quote from the collected evidence (limit to 200 chars).
    4. 'Relevance_Type': The legal type of contradiction (PERJURY, CONTEMPT, ENDANGERMENT, FINANCIAL_INSTABILITY, SUBSTANCE_ABUSE, ASSAULT).
    """
    
    try:
        response = client.models.generate_content(
            model='gemini-2.0-flash-exp', # Use latest model for best analysis
            contents=prompt,
            config=genai.types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema={"type": "array", "items": {"type": "object", "properties": {
                    "Filing_ID": {"type": "string"},
                    "Contradicted_Statement": {"type": "string"},
                    "Evidence_Snippet": {"type": "string"},
                    "Relevance_Type": {"type": "string"}
                }}}
            )
        )
        
        # Parse the JSON response
        results = json.loads(response.text)
        contradictions.extend(results)
        print(f"   Found {len(results)} potential contradictions")
        return pd.DataFrame(results)

    except APIError as e:
        print(f"Gemini API Error: {e}")
        return pd.DataFrame()
    except Exception as e:
        print(f"An error occurred during analysis: {e}")
        return pd.DataFrame()

def run_ai_analyzer():
    """Main function to run all contradiction checks."""
    global MASTER_CSV
    MASTER_CSV = find_latest_evidence_file()
    if not MASTER_CSV:
        print("❌ Error: No evidence CSV file found in the 'output' directory.")
        print("Please run the OCR evidence processor first.")
        return
    df_evidence = load_evidence(MASTER_CSV)    
    if df_evidence is None:
        return

    all_reports = []

    # Iterate through all key filings/statements you want to challenge
    for name, statement in APPLICANT_FILINGS.items():
        report_df = analyze_for_contradiction(df_evidence, name, statement)
        if not report_df.empty:
            all_reports.append(report_df)

    if all_reports:
        final_report = pd.concat(all_reports, ignore_index=True)
        final_report.to_csv(ANALYSIS_OUTPUT_CSV, index=False)
        print(f"\n✅ AI Contradiction Report saved to: {ANALYSIS_OUTPUT_CSV}")
        print("Review this report for critical evidence of perjury and contempt.")
    else:
        print("\nℹ️ No major contradictions detected, or insufficient evidence data.")

if __name__ == "__main__":
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
    
    print("🤖 AI Legal Contradiction Analyzer")
    print("=" * 50)
    print("Analyzing Harper's evidence for contradictions...")
    # The evidence file will be printed when run_ai_analyzer is called
    print(f"Output will be saved to: {ANALYSIS_OUTPUT_CSV}")
    print()
    
    run_ai_analyzer()